services:
  sshkube-server:
    build: server
    image: u8sand/sshkube-server:0.1.0
    configs:
      - source: github-users
        target: /data/users
    ports:
      - 22/tcp
    volumes:
      - sshkube-server-hostkeys:/data/ssh-host-keys

volumes:
  sshkube-server-hostkeys:

configs:
  github-users:
    content: |
      u8sand
